In [1]:
import streamlit as st
import pymysql
import os
# from dotenv import load_dotenv
# load_dotenv('.env')  # take environment variables from .env.
import datetime
import T5_funcs as T5f
import take5_functions as t5f
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from dash import Dash, html
import dash_ag_grid as dag 
from st_aggrid import AgGrid
from helper import *
from sklearn.linear_model import LinearRegression
import hmac

In [8]:
# Get the directory of the current script
cwdir = "G:/My Drive/kordis/T5OIL_SL_DOCKER_EC2"
cwdirup1 = os.path.dirname(cwdir)
# st.write(cwdir)
controlmap = pd.read_excel(cwdir + '/control_map.xlsx', index_col=None)
extra = pd.read_csv(cwdir + '/t5_extra_data.csv', index_col=None)
workdays = pd.read_csv(cwdir + '/t5_workdays.csv', index_col=None)

In [10]:
locations = [(1402,'1402 - Ten Mile'), 
            (1403, '1403 - Caldwell'), 
            (1404, '1404 - Glenwood'), 
            (1405, '1405 - Ontario'), 
            (1407, '1407 - Pasco'), 
            (1881, '1881 - Lacey')]
loc_df = pd.DataFrame(locations, columns=['Location', 'location'])
loc_df['Location'] = loc_df['Location'].astype('int64')

extra = extra.merge(loc_df, how='left', on='Location')

extra['Date'] = pd.to_datetime(extra.Date, format='%y-%b', errors='coerce')
workdays['date'] = pd.to_datetime(workdays.date, format='%b-%y', errors='coerce')#.dt.strftime('%b %y')
# st.write(workdays)

# get secrets from st.secrets
host = st.secrets["host"]#os.getenv('host') 
user = st.secrets["user"]#os.getenv('user')
port = st.secrets["port"]#os.getenv('port')
password = st.secrets["password"]#os.getenv('password')
databasename = st.secrets["databasename"]#os.getenv('databasename')

#### read in data
connection = T5f.make_connection(host, user, port, password, databasename)
df = T5f.read_in_SQL(connection)

df = df.loc[(df.location != 'Admin') & (df.location != 'Not Specified') & (df.location != 'Saranac'),:]


#### get data within dates. Baseline is 13 months.
maxdate = max(df.monthdt)
mindate = maxdate - pd.DateOffset(months=12)

with st.sidebar:
    options = st.multiselect('Select the Take 5 Oil Locations you want to perform analsysis on:', 
                            df.location.unique(), df.location.unique())
    startdate = st.date_input("Please enter a starting date (must pick 1st of month):", mindate.date())
    enddate = st.date_input("Please enter a ending date:", maxdate.date())
startdate = pd.to_datetime(startdate)
enddate = pd.to_datetime(enddate)

# trim data based on selected/standard dates
df_new = df[(df['monthdt'] >= startdate) & (df['monthdt'] <= enddate) & (df.location.isin(options))]

ext_melt = pd.melt(extra, 
                     id_vars=['Location', 'location', 'Date'], 
                     var_name='metric', 
                     value_name='value').dropna(subset=['value'])
ext_melt = ext_melt[(ext_melt.location.isin(options))]

ext_avg = ext_melt[(ext_melt['Date'] >= startdate) & 
                   (ext_melt['Date'] <= enddate) & 
                   (ext_melt.metric.isin(['BayTimes','Pmix_perc','Big5_perc']))]
ext_sum = ext_melt[(ext_melt['Date'] >= startdate) & 
                   (ext_melt['Date'] <= enddate) & 
                   (ext_melt.metric.isin(['CarsServ','EmpHours']))]

workdays = workdays[(workdays['date'] >= startdate) & 
                    (workdays['date'] <= enddate)]


#### create monthly pivot table and display. 
pivot_df = T5f.create_T5_pivot_table(result_df=df_new, ext_avg=ext_avg, 
                                     ext_sum=ext_sum, controlmap=controlmap,
                                     workdays=workdays)

print(pivot_df)



ind = (df['monthdt'] >= enddate - pd.DateOffset(months=1)) & (df['monthdt'] <= enddate)
df2months = df[ind]

st.write('here is the df2months df:', df2months)

df_loc = df_new[ind].groupby(['location','monthdt'])['value'].mean()#.reset_index()
st.write(df_loc)
    # + row2 + row3 + row4+ row5 + row6 + row7:
    # tile = col.container(height=60)
    # tile.title(":balloon:")


# ind_sum = [(11, 'Revenue'),    (12, 'Gross Profit'), (25, '4-Wall EBITDA'), 
#             (26, '4-Wall FCF'), (27, 'Net Profit'),   (71, '# of Cars Serviced')    ]
# ind_avg = [( 1, 'CPD'),            ( 2, 'ARO'),              (21, 'Labor %'),
#             (22, 'Controllable %'),(23, 'Uncontrollable %'), (31, 'Cash'),
#             (41, 'Gross Profit %'),(42, '4-Wall EBITDA %'),  (43, '4-Wall FCF %'),
#             (44, 'Net Profit %'),  (51, 'LHPC'),             (52, 'Revenue Per Employee Hours Worked'),
#             (61, 'P-Mix %'),       (62, 'Big 5 %'),          (63, 'Bay Times'),
#             (64, 'Discount %'),    (72, 'Gross Profit Per Car'), (73, '4-Wall EBITDA Per Car')]

OperationalError: (2003, "Can't connect to MySQL server on 'db3.c1e8m6quouwo.us-east-1.rds.amazonaws.com' (timed out)")

In [9]:
###### crate dataframes for figures
#### create revenue by location dataframe
ind = (df_new.Account_Num >4000) & (df_new.Account_Num <4999)
df_rev = df_new[ind].groupby(['location','monthdt'])['value'].sum()#.reset_index()
tot_rev_by_date = df_rev.reset_index().groupby('monthdt')['value'].sum().reset_index()


#### create # of cars serviced dataframe
ext_cars_by_loc = ext_melt[ext_melt.metric == 'CarsServ']
tot_cars_by_date = ext_cars_by_loc.groupby('Date')['value'].sum().reset_index()

#### create gross profit dataframe
ind = (df_new.Account_Num >5000) & (df_new.Account_Num <5998)
df_cogs = df_new[ind].groupby(['location','monthdt'])['value'].sum()#.reset_index()
df_gross = df_rev - df_cogs
tot_gross_by_date = df_gross.reset_index().groupby('monthdt')['value'].sum().reset_index()
# st.write(df_gross)

#### create 4-wall EBITDA dataframe
ind = (df_new.Account_Num >6000) & (df_new.Account_Num <7999)
df_4wexpenses = df_new[ind].groupby(['location','monthdt'])['value'].sum()#.reset_index()
df_4webitda = df_gross - df_4wexpenses
tot_ebitda_by_date = df_4webitda.reset_index().groupby('monthdt')['value'].sum().reset_index()

#### create Cash dataframe
ind = (df_new.Account_Num >1000) & (df_new.Account_Num <1099)
df_cash = df_new[ind].groupby(['location','monthdt'])['value'].sum()#.reset_index()
tot_cash_by_date = df_cash.reset_index().groupby('monthdt')['value'].sum().reset_index()

#### create 4-wall EBITDA per car dataframe
# st.write(ext_cars_by_loc)
# st.write(df_4webitda)
extcarsloc = ext_cars_by_loc.copy()
extcarsloc.rename(columns={'Date': 'monthdt'}, inplace=True)
ext_cars_loc = extcarsloc.set_index(['location','monthdt'])['value']
df_ebitda_by_car = df_4webitda / ext_cars_loc
# st.write(df_ebitda_by_car)
tot_ebitdacar_by_date = df_ebitda_by_car.reset_index().groupby('monthdt')['value'].sum().reset_index()


st.write("df revenue:", df_rev)
st.write("cars by loc:", ext_cars_by_loc)
st.write("ARO: ", df_rev / ext_cars_by_loc)
st.write("df revenue:", df_rev)

NameError: name 'df_new' is not defined